name: on pull request

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ GITHUB_REF }}!"

